### ISSUE TITLE
Can't configure locally?

### ISSUE THREAD

**Issue by briannehinchliffe** [SaschaGalley/grunt-phpcs#52]
I’m trying to incorporate grunt-phpcs into our grunt build process, but it seems that this requires a system-wide install of phpcs (https://github.com/squizlabs/PHP_CodeSniffer#installation).

It’d be optimal to use it with the 'curl' method and have grunt-phpcs point to the phpcs.phar file for processing. How can we configure grunt-phpcs to do that?

We're using: Grunt, Bower, npm

We would like to have the sniffer run on WordPress standards as well.

**Comment by jeremiahsmall** [comment]
I can report that it works with composer install. It seems that as long as you have the path to the phpcs executable correct, it should work for any installation method. This is how I have it configured with Composer. Hope this helps:

```
        options: {
            bin: 'vendor/bin/phpcs',
            standard: 'PSR2',
            encoding: 'utf-8',
            verbose: false
        }
```

**Comment by briannehinchliffe** [comment]
We ended up switching the bin's path to the binary and it worked just fine

bin: 'bower_components/phpcs/scripts/phpcs'
